### ISSUE TITLE
XIV Combo Expanded - (Between the) Ley Lines doesn't work

### ISSUE THREAD

**Issue by LittleNightmare** [daemitus/MyDalamudPlugins#1]
I not sure it is my game problem or not because I'm using it on cn server. (this function work when I using the origin plugin) Other functions work well ( at least I haven't found them)

**Comment by daemitus** [comment]
I don't have the levels to test it myself, but the code is basically the
same from the original to mine. Does it always not work?

**Comment by LittleNightmare** [comment]
the original one is working (v.1.0.3.6)

**Comment by daemitus** [comment]
I asked a friend to check, works fine for them. Try disabling all your other plugins and reinstalling just combo, see what happens.

cut/paste everything from `C:\Users\<username>\AppData\Roaming\XIVLauncher\installedPlugins` elsewhere, load the game, reinstall the plugin, make sure the combo is checked and see if it works or not.

**Comment by LittleNightmare** [comment]
not work :( it doesn't make sense. Athough, I notice there is an update of the signature for 5.4, other features work well. Moreover, I just download xiv combo v1.0.3.8 (Between the), Ley Lines still working. I find you are using [BuffVTableAddr ](https://github.com/daemitus/XIVComboPlugin/blob/b8e6d840cdecdf748d4234f5fc829a7ccbb3a093/XIVComboPlugin/PluginAddressResolver.cs#L26) but i haven't found it in the origin plugin. However, this plugin work well when i using RDM.

**Comment by LittleNightmare** [comment]
it work ?_?  IDK why?

**Comment by daemitus** [comment]
who knows. let me know if it breaks again :D

**Comment by LittleNightmare** [comment]
if you just log in, this problem would happen

fix:
1. go to another area
2. use Ley Lines (~~in my testing, if I don't use Ley Lines, other steps do not work~~ sometime work, maybe just need more time?)
3. switch to another job
4. switch back to BLM
