### ISSUE TITLE
Are these plugins still being updated?

### ISSUE THREAD

**Issue by jyudt** [daemitus/MyDalamudPlugins#13]
I don't mean to rush the dev but if these things are being discontinued I'd like to move on.

**Comment by MKhayle** [comment]
Daemitus has stopped playing FFXIV and transfers his projects' ownership to several people who volunteers. 

- [XIVCombo Expanded](https://github.com/MKhayle/XIVComboPlugin) has been updated already on the current repository and I am its new owner.
- [YesAlready](https://puni.sh/plugin/YesAlready) is now available (and updated for 6.5) on the puni.sh repository 
- EZWondrousTails is available on the main repository of Dalamud (doesn't require an external repository anymore)
- [SomethingNeedsDoing](https://github.com/daemitus/SomethingNeedDoing) is up for adoption !

**Comment by jyudt** [comment]
Okay, thanks for the quick response.

**Comment by MKhayle** [comment]
I updated this repo's README in case of future inquiries.
