### ISSUE TITLE
YesAlready api4 1.1.0 issues

### ISSUE THREAD

**Issue by vaoan** [daemitus/MyDalamudPlugins#4]
YesAlready seems o have issues in the new version. 1.0 was working fine.
![ffxiv_dx11_Tj3DWvyFve](https://user-images.githubusercontent.com/3722960/135150424-961b7422-7f48-41c2-bba2-666d266e9215.png)

**Comment by daemitus** [comment]
Known issue, hoping to fix tonight

**Comment by daemitus** [comment]
updated!

**Comment by daemitus** [comment]
updated!
