### ISSUE TITLE
CameraPlugin

### ISSUE THREAD

**Issue by Kwehh13** [daemitus/MyDalamudPlugins#5]
Probably not the right place for this but - do you have any plans to revive cameraplugin? Not sure if it included it but personally I'm looking for a draw distance plugin so I can change how far away I see objects and people, maybe with an option to cap the amount of things shown at once - or even better an option to change it based on conditions such as in town etc.

Also, I love your plugins, honestly I'm about to start fanning all over your plugins. I always wanted to code myself but I'm dumb as hell and what you do just amazes me - although idk how hard all this is to begin with, could be a walk in the park for you

**Comment by daemitus** [comment]
Use cammy

**Comment by daemitus** [comment]
https://github.com/UnknownX7/Cammy

**Comment by Kwehh13** [comment]
do you think its possible to change code draw distance?

**Comment by daemitus** [comment]
more than likely yes, but only for what's already present in the table.

**Comment by Kwehh13** [comment]
hmm i see. I wanna be able to see people and objects further away cause I recently realised the draw distance is so incredibly tiny, or at least feels tiny to me
