### ISSUE TITLE
Missing MiniCactpotSolver

### ISSUE THREAD

**Issue by tswinehart** [daemitus/MyDalamudPlugins#9]
Unable to install ezMiniCactpot as it's not listed in https://raw.githubusercontent.com/daemitus/MyDalamudPlugins/master/pluginmaster.json

**Comment by daemitus** [comment]
It's broken on the main repo, you can get it from there once goat fixes
things

**Comment by SaltFish-X** [comment]
https://raw.githubusercontent.com/daemitus/MyDalamudPlugins/CN/pluginmaster.json
ezMiniCactpot and FauxHollowsSolver is miss too
I very like they，hope fix they soon
thank you
